forceLoad:
    - lobby
    - test/awkward

lobbySettings:
    lobby: true
    chat: true
    crownsolo: false
    visible: true
    color: "#73b3cc"
    color2: "#273546"

defaultSettings:
    chat: true
    crownsolo: false
    color: "#3b5054"
    color2: "#001014"
    visible: true

lobbyRegexes:
    - "^lobby[1-9]?[1-9]?$"
    - "^test/.+$"

lobbyBackdoor: "lolwutsecretlobbybackdoor"
fullChannel: "test/awkward"
