forceLoad:
    - lobby
    - test/awkward

lobbySettings:
    lobby: true
    chat: true
    crownsolo: false

lobbyRegexes:
    - "^lobby\\d\\d$"
    - "^test/.*$"

lobbyBackdoor: "lolwutsecretlobbybackdoor"
