user:
    normal:
        a: 1500
        m: 50
        ch: 1000
    chains:
        userset:
            interval: 1800000,
            num: 1000
crown:
    normal:
        a: 600
        m: 50
    chains:
        userset:
            interval: 1800000,
            num: 1000
admin:
    normal:
        a: 120
        m: 16.6666666667
    chains:
        userset:
            interval: 1800000,
            num: 1000
