defaultName: Anonymous
defaultFlags:
    volume: 100
enableColorChanging: false
enableCustomNoteData: true
adminParticipant:
    _id: "0"
    name: mpp
    color: "#fff"
    id: "0"
enableAdminEval: false
